[env]
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson ; сериализация json
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor

[env:esp32dev]
platform = espressif32
board = esp32dev
monitor_filters = esp32_exception_decoder
board_build.filesystem = littlefs
board_build.f_cpu = 240000000L